//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace udemy_mvc_cv.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class udemy_mvc_cvEntities : DbContext
    {
        public udemy_mvc_cvEntities()
            : base("name=udemy_mvc_cvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblAdmin> TblAdmins { get; set; }
        public virtual DbSet<TblDeneyimler> TblDeneyimlers { get; set; }
        public virtual DbSet<TblEgitimler> TblEgitimlers { get; set; }
        public virtual DbSet<TblHakkimda> TblHakkimdas { get; set; }
        public virtual DbSet<TblHobiler> TblHobilers { get; set; }
        public virtual DbSet<TblIletisim> TblIletisims { get; set; }
        public virtual DbSet<TblSertifikalar> TblSertifikalars { get; set; }
        public virtual DbSet<TblYetenekler> TblYeteneklers { get; set; }
        public virtual DbSet<TblSosyalMedya> TblSosyalMedya { get; set; }
    }
}
